### ISSUE TITLE
Resultado de Marcadores - Excluir "Some" Lista de Marcadores

### ISSUE THREAD

**Issue by cjvaz** [ComunidadeExpresso/expressomail#17]
Ao excluir um email da lista do resultado de e-mails de um marcador, some a lista de marcadores abaixo da árvore de pastas do Expresso. Volta ao clicar em atualizar.

**Caso de teste:**
1. Clicar em um marcador da lista abaixo da árvore de pastas;
2. Selecionar um e-mail que aparece no resultado da busca e excluir; <- Aqui desaparece a lista de marcadores.
3. Clica em atualizar e volta ao normal;

**Comment by mauricioviani** [comment]
Carlos, seu pullrequest está de acordo com a sistemática que combinamos até agora. Vi que você criou um branch específico no seu fork e a partir dele fez o pullrequest. Agora que foi aceito você pode excluir o branch se quiser (acho recomendável). No comentário do commit faltou o número do ticket redmine, está escrito '(remine)'.

**Comment by cjvaz** [comment]
Legal! Depois do fork também notei que esqueci o número do ticket. Mas vamos melhorando o processo. Abs
